#!/usr/bin/env sh

set -euo pipefail

REPOSITORY=$HOME/repositories/dotfiles

function prepare_directory () {
  local file_name=$1
  local directory_path=$(dirname ${file_name})
  mkdir -p ${directory_path}
}

files_to_link="
  .gitconfig
  .ssh/config
  .vimrc
  .zshrc
"
for file_to_link in ${files_to_link}; do
  link_file=$HOME/${file_to_link}

  if [ -e "${link_file}" ]; then
    continue
  fi

  prepare_directory ${link_file}
  ln -s $REPOSITORY/${file_to_link} ${link_file}
done

files_to_copy="
  .bin/update
"
for files_to_copy in ${files_to_copy}; do
  file=$HOME/${files_to_copy}

  prepare_directory ${link_file}
  cp $REPOSITORY/${files_to_copy} ${file}
done

if [ -x "$(command -v brew)" ]; then
  brew install \
    aquaproj/aqua/aqua \
    asdf \
    git \
    peco \
    stern \
    terraform \
    tree \
    vim
fi

if [ -x "$(command -v asdf)" ]; then
  # https://github.com/rbenv/ruby-build/wiki#suggested-build-environment
  brew install openssl readline
  asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git

  asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
fi
