#!/usr/bin/env bash

set -euo pipefail

REPOSITORY=$HOME/repositories/dotfiles

function prepare_directory () {
  local file_name=$1
  local directory_path=$(dirname ${file_name})
  mkdir -p ${directory_path}
}

files_to_link="
  .bashrc
  .gitconfig
  .ssh/config
  .tool-versions
  .vimrc
  .zshrc
"
for file_to_link in ${files_to_link}; do
  link_file=$HOME/${file_to_link}

  if [ -L "${link_file}" ]; then
    continue
  fi

  if [ -f "${link_file}" ]; then
    if [ "${file_to_link}" = '.bashrc' ]; then
      anchor="# from dotfiles"
      if ! grep -q "${anchor}" ${link_file}; then
        echo '' >> ${link_file}
        echo ${anchor} >> ${link_file}
        echo ". $REPOSITORY/${file_to_link}" >> ${link_file}
      fi
      continue
    else
      echo "warn: Remove ${link_file} which is a file!"
      rm -f ${link_file}
    fi
  fi

  prepare_directory ${link_file}
  ln -s $REPOSITORY/${file_to_link} ${link_file}
done

if [ ! -f "$HOME/.ssh/id_ed25519.pub" ]; then
  echo "1) tadatoshi.tokutake@gmail.com"
  echo "2) ttokutake@quipper.com"
  read -p "Choose your email address: " num
  case $num in
      1)
        email="tadatoshi.tokutake@gmail.com"
        ;;
      *)
        email="ttokutake@quipper.com"
        ;;
  esac
  ssh-keygen -t ed25519 -C $email
fi

if [ -x "$(command -v apt-get)" ]; then
  sudo apt install -y \
    bash-completion \
    curl \
    git \
    keychain \
    tree \
    vim

  read -p 'Do you install mise? [y/n]: ' bool
  case $bool in
    y | yes)
      curl https://mise.run | sh
      eval "$(~/.local/bin/mise activate bash)"
      ;;
    *)
      ;;
  esac
fi

if [ -x "$(command -v brew)" ]; then
  brew install \
    aquaproj/aqua/aqua \
    git \
    mise \
    peco \
    stern \
    terraform \
    tree \
    vim \
    xsel
fi

if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

files_to_copy="
  .bin/update
"
for file_to_copy in ${files_to_copy}; do
  file=$HOME/${file_to_copy}

  prepare_directory ${file}
  cp $REPOSITORY/${file_to_copy} ${file}
done

if [ -x "$(which mise)" ]; then
  if [[ "$SHELL" == */bash ]]; then
    mise use -g usage
    # This requires bash-completion to be installed
    mkdir -p /etc/bash_completion.d/
    mise completion bash --include-bash-completion-lib | sudo tee /etc/bash_completion.d/mise > /dev/null
    sudo sed -i -e \
      's/    \. "$_comp_init_startup_config"/    if [[ "$_comp_init_startup_config" != *\/mise ]]; then\n        . "$_comp_init_startup_config"\n    fi/' \
      /etc/bash_completion.d/mise
  fi
fi
