#!/usr/bin/env bash

set -euo pipefail

if [ -x "$(command -v apt-get)" ]; then
  sudo apt update
  sudo apt dist-upgrade -y
  sudo apt autopurge -y
  sudo apt autoclean
fi

if [ -x "$(command -v brew)" ]; then
  brew upgrade
fi

if [ -x "$(command -v mise)" ]; then
  if [ ! -x "$(command -v brew)" ]; then
    mise self-update
  fi
fi

if [ -x "$(command -v vim)" ]; then
  vim -c :PlugUpdate -c :PlugUpgrade -c :qa
fi

echo
echo
echo
echo 'if you use on-my-zsh, enter "omz update"!'
