#!/usr/bin/env bash

set -euo pipefail

if [ -x "$(command -v apt-get)" ]; then
  sudo apt update
  sudo apt dist-upgrade -y
  sudo apt autopurge -y
  sudo apt autoclean
fi

if [ -x "$(command -v brew)" ]; then
  brew upgrade
fi

if [ -x "$(command -v asdf)" ]; then
  if [ -f "$HOME/.asdf/asdf.sh" ]; then
    asdf update
  fi
  asdf plugin update --all
fi
